name: animetrace
description: 漫迹
publish_to: "none"
version: 1.14.0
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  reorderables: ^0.6.0
  pinyin: ^3.3.0
  flutter_logkit:
    git:
      url: https://github.com/linyi102/flutter_logkit.git
      ref: 4c99a6e9
  super_sliver_list: ^0.4.1
  queue: ^3.1.0+2
  darty_json: ^1.0.5
  version: ^3.0.2
  lottie: ^2.6.0
  desktop_drop: ^0.4.4
  flutter_svg: ^2.0.7
  animations: ^2.0.7
  flutter_markdown: ^0.6.15
  get_time_ago: ^1.1.6
  bot_toast: ^4.0.3
  timer_count_down: ^2.2.2
  sliver_tools: ^0.2.9
  pull_to_refresh: ^2.0.0
  ming_cute_icons: ^0.0.2
  reorderable_grid_view: ^2.2.7
  photo_view: ^0.14.0
  flutter_rating_bar: ^4.0.1
  window_manager: ^0.2.5
  percent_indicator: ^4.2.2
  expand_widget: ^3.1.1
  get: ^4.6.5
  shared_preferences:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_packages.git
      path: packages/shared_preferences/shared_preferences
  sqflite:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_sqflite.git
      path: ./sqflite
  file_picker:
    git:
      url: https://gitcode.com/openharmony-sig/fluttertpc_file_picker
  webdav_client: ^1.1.8
  dio: ^5.8.0+1
  html: ^0.15.0
  fast_cached_network_image: 1.2.9
  archive: ^3.1.8
  path: ^1.8.0
  package_info_plus:
    git:
      url: https://gitcode.com/openharmony-sig/flutter_plus_plugins.git
      path: packages/package_info_plus/package_info_plus
  url_launcher:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      path: packages/url_launcher/url_launcher
  transparent_image: ^2.0.0

dependency_overrides:
  # 覆盖cached_network_image等其他包使用的path_provider
  path_provider:
    git:
      url: https://gitcode.com/openharmony-tpc/flutter_packages.git
      ref: HEAD
      path: packages/path_provider/path_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.14.3"
  shell_executor:
    git:
      url: https://github.com/linyi102/shell_executor
      ref: main

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-round.png
    - assets/images/website/
    - assets/icons/
    - assets/lotties/

flutter_assets:
  assets_path: assets/
  output_path: lib/values/
  filename: assets.dart
  field_prefix:

flutter_gen:
  output: lib/values/

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"
