name: animetrace
description: 漫迹
publish_to: "none"
version: 1.12.3
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_logkit:
    git:
      url: https://github.com/linyi102/flutter_logkit.git
      ref: v0.0.1
  super_sliver_list: ^0.4.1
  queue: ^3.1.0+2
  darty_json: ^1.0.5
  hotkey_manager: ^0.1.8
  flex_color_picker: ^3.3.0
  emoji_picker_flutter: ^1.6.3
  version: ^3.0.2
  lottie: ^2.6.0
  media_kit: 1.1.10+1
  media_kit_video: 1.2.4
  media_kit_libs_android_video: 1.3.6
  media_kit_libs_windows_video: 1.0.9
  media_kit_native_event_loop: 1.0.8
  desktop_drop: ^0.4.4
  flutter_svg: ^2.0.7
  animations: ^2.0.7
  app_installer: ^1.1.0
  flutter_markdown: ^0.6.15
  get_time_ago: ^1.1.6
  bot_toast: ^4.0.3
  flex_color_scheme: ^7.2.0
  timer_count_down: ^2.2.2
  file_saver: ^0.1.1
  sliver_tools: ^0.2.9
  pull_to_refresh: ^2.0.0
  ming_cute_icons: ^0.0.2
  reorderable_grid_view: ^2.2.7
  webview_flutter: ^3.0.4
  photo_view: ^0.14.0
  flutter_rating_bar: ^4.0.1
  window_manager: ^0.2.5
  percent_indicator: ^4.2.2
  dart_ping: ^6.1.2
  expand_widget: ^3.1.1
  get: ^4.6.5
  shared_preferences: ^2.0.9
  sqflite: ^2.0.1
  sqflite_common_ffi: ^2.1.0
  path_provider: ^2.0.8
  file_picker: ^9.0.0
  webdav_client: ^1.1.8
  dio: ^4.0.4
  html: ^0.15.0
  cached_network_image: ^3.2.3
  archive: ^3.1.8
  path: ^1.8.0
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.14.3"

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-round.png
    - assets/images/website/
    - assets/icons/
    - assets/lotties/

flutter_assets:
  assets_path: assets/
  output_path: lib/values/
  filename: assets.dart
  field_prefix:

flutter_gen:
  output: lib/values/

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/logo.png"
