name: flutter_test_future # 和包相关
description: 漫迹

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.12.3

environment:
  sdk: ">=3.3.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_logkit:
    git:
      url: https://github.com/linyi102/flutter_logkit.git
      ref: v0.0.1
  super_sliver_list: ^0.4.1
  queue: ^3.1.0+2
  darty_json: ^1.0.5
  hotkey_manager: ^0.1.8
  flutter_picker: ^2.1.0
  flex_color_picker: ^3.3.0
  emoji_picker_flutter: ^1.6.3
  version: ^3.0.2
  lottie: ^2.6.0
  media_kit: 1.1.10+1
  media_kit_video: 1.2.4
  media_kit_libs_android_video: 1.3.6
  media_kit_libs_windows_video: 1.0.9
  media_kit_native_event_loop: 1.0.8
  desktop_drop: ^0.4.4
  flutter_svg: ^2.0.7
  animations: ^2.0.7
  app_installer: ^1.1.0
  flutter_markdown: ^0.6.15
  get_time_ago: ^1.1.6
  bot_toast: ^4.0.3
  flex_color_scheme: ^7.2.0
  timer_count_down: ^2.2.2
  file_saver: ^0.1.1
  sliver_tools: ^0.2.9
  pull_to_refresh: ^2.0.0
  ming_cute_icons: ^0.0.2
  reorderable_grid_view: ^2.2.7
  webview_flutter: ^3.0.4
  photo_view: ^0.14.0
  flutter_rating_bar: ^4.0.1
  window_manager: ^0.2.5
  percent_indicator: ^4.2.2
  dart_ping: ^6.1.2
  expand_widget: ^3.1.1
  get: ^4.6.5
  shared_preferences: ^2.0.9
  sqflite: ^2.0.1
  sqflite_common_ffi: ^2.1.0
  path_provider: ^2.0.8
  file_picker:
    git: https://github.com/linyi102/flutter_file_picker_no_cache.git
  webdav_client: ^1.1.8
  dio: ^4.0.4
  html: ^0.15.0
  cached_network_image: ^3.2.3
  archive: ^3.1.8
  path: ^1.8.0
  package_info_plus: ^4.0.2
  url_launcher: ^6.1.0
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/website/
    - assets/icons/
    - assets/lotties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

  #  fonts:
  #    - family: myfont
  #      fonts:
  #        - asset: assets/fonts/Alibaba-PuHuiTi-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_assets:
  assets_path: assets/
  output_path: lib/values/
  filename: assets.dart
  field_prefix:

flutter_gen:
  output: lib/values/
