name: animetrace_default
description: 漫迹
publish_to: "none"
version: 1.17.3

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animetrace:
    path: ../..
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: "../../assets/images/logo.png"
